# Generated by Django 5.2.7 on 2025-10-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nota_aprobacion', models.FloatField(default=55.0)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ponderacion', models.FloatField()),
                ('ramo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.ramo')),
            ],
        ),
    ]
