# Generated by Django 5.2.7 on 2025-10-16 02:27
from django.db import migrations
import os

def crea_superusuario(apps, schema_editor):
    User = apps.get_model('auth', 'User')

    # Lee las credenciales de las variables de entorno de Render
    DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD')
    DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL')

    # Crea el superusuario solo si no existe
    if not User.objects.filter(username=DJANGO_SUPERUSER_USERNAME).exists():
        print(f"Creando cuenta para superusuario {DJANGO_SUPERUSER_USERNAME}")
        User.objects.create_superuser(
            username=DJANGO_SUPERUSER_USERNAME,
            password=DJANGO_SUPERUSER_PASSWORD,
            email=DJANGO_SUPERUSER_EMAIL
        )

class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(crea_superusuario),
    ]